# Generated by Django 4.2.7 on 2025-07-30 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservicelog',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.studytopic'),
        ),
    ]
